# Generated by Django 4.1 on 2022-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('childs_name', models.TextField()),
                ('relationship', models.CharField(max_length=50)),
                ('childs_age', models.IntegerField()),
            ],
        ),
    ]
