# Generated by Django 4.1 on 2022-08-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_psychomotor1_psychomotor2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cognitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
                ('q11', models.TextField()),
            ],
        ),
    ]
